services:
  gc:
    build:
      context: .
      dockerfile: gc/Dockerfile
    image: gc
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: ["dotnet", "run", "--project", "gc/gc.csproj", "--", "--help"]

  gc-test:
    build:
      context: .
      dockerfile: gc/Dockerfile
    image: gc
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: ["dotnet", "test", "gc.tests/gc.tests.csproj"]

  gc-bash:
    build:
      context: .
      dockerfile: gc/Dockerfile
    image: gc
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: ["/bin/bash"]
    stdin_open: true
    tty: true
